export const NexusEventType = {
  CONTEXT_UPDATED: "CONTEXT_UPDATED",

  SESSION_STARTED: "SESSION_STARTED",
  SESSION_ENDED: "SESSION_ENDED",
  FOCUS_CHANGED: "FOCUS_CHANGED",

  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_STARTED: "TASK_STARTED",
  TASK_COMPLETED: "TASK_COMPLETED",
  TASK_DEFERRED: "TASK_DEFERRED",
  TASK_ABANDONED: "TASK_ABANDONED",

  USER_STATE_CHANGED: "USER_STATE_CHANGED",
  PREFERENCE_CHANGED: "PREFERENCE_CHANGED",
  PREFERENCE_RESET: "PREFERENCE_RESET",

  PREDICTION_REQUESTED: "PREDICTION_REQUESTED",
  PREDICTION_UPDATED: "PREDICTION_UPDATED",

  RECOMMENDATION_GENERATED: "RECOMMENDATION_GENERATED",

  DECISION_CREATED: "DECISION_CREATED",
  DECISION_UPDATED: "DECISION_UPDATED"
} as const;

export type NexusEventType =
  typeof NexusEventType[keyof typeof NexusEventType];
